### PR TITLE
rearranged files

### PR DESCRIPTION
**Pull request by cyng24**

### CODE REVIEW

**Comment by gracemgately** [comment]
there seems to be an extra seed.js file in the root of the project that is never run?

**Comment by cyng24** [comment]
The seed file hasn't been used yet. We're just creating it at the moment.

**Comment by gracemgately** [comment]
Since there is already a seed file in the scripts folder, and that is the one that is being run for 'npm run seed,' I would recommend that the in-progress one in the root directory not be included until it's  ready to be added to the master branch -- it can even be a separate issue if that helps keep it clear.

**Comment by cyng24** [comment]
We removed the extra seed from the main folder and pushed it. Do I need to submit a new pull request?

**Comment by gracemgately** [comment]
It looks like it -- let me close this one and when you submit the new one I'll merge it right away.

**Pull request closed without merging**
